import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Zap, Calendar, ArrowRight, Loader2, RefreshCw } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { getAIResponse, extractJSON } from '../lib/ai';

interface Props {
    lang: 'en' | 'uz';
}

interface PlanItem {
    day: number;
    title: string;
    description: string;
    duration: string;
    focus: string;
}

const Plan = ({ lang }: Props) => {
    const [plan, setPlan] = useState<PlanItem[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    const generateAIPlan = async () => {
        setLoading(true);
        setError(null);
        try {
            const { data: { user } } = await supabase.auth.getUser();
            if (!user) throw new Error("Not logged in");

            let { data: profile } = await supabase.from('profiles').select('*').eq('id', user.id).single();

            // If profile doesn't exist, create a basic one or use defaults
            if (!profile) {
                profile = {
                    current_level: 'B1',
                    target_level: 'C1',
                    weakness: 'Writing',
                    frequency: 'Daily',
                    time_left: '1 month'
                } as any;
            }

            const prompt = `
                Act as an expert CEFR English Tutor. Create a 7-day study plan snippet (for a 30-day roadmap) for a student with these details:
                - Current Level: ${profile?.current_level || 'B1'}
                - Target Level: ${profile?.target_level || 'C1'}
                - Weakness: ${profile?.weakness || 'General'}
                - Study Frequency: ${profile?.frequency || 'Daily'}
                - Time left until exam: ${profile?.time_left || '1 month'}

                Return ONLY a JSON array of objects with this structure:
                [{ "day": 1, "title": "string", "description": "string", "duration": "string", "focus": "string" }]
                Language: ${lang === 'en' ? 'English' : 'Uzbek (lotin)'}
            `;

            const resText = await getAIResponse(prompt);

            // Extract JSON safely
            const parsedPlan = extractJSON(resText);
            setPlan(parsedPlan);

            // Save to DB (wrapped in separate try-catch to prevent UI block if column missing)
            try {
                await supabase.from('profiles').update({ study_plan: parsedPlan }).eq('id', user.id);
            } catch (dbErr) {
                console.warn("DB Update failed (likely missing study_plan column):", dbErr);
            }
        } catch (err: any) {
            console.error("AI Plan Error:", err);
            setError(lang === 'en' ? "Failed to generate plan. Please try again." : "Reja yaratib bo'lmadi. Qayta urinib ko'ring.");
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        const fetchExistingPlan = async () => {
            const { data: { user } } = await supabase.auth.getUser();
            if (user) {
                const { data } = await supabase.from('profiles').select('study_plan').eq('id', user.id).single();
                if (data?.study_plan && Array.isArray(data.study_plan)) {
                    setPlan(data.study_plan);
                    setLoading(false);
                } else {
                    generateAIPlan();
                }
            }
        };
        fetchExistingPlan();
    }, []);

    return (
        <motion.div
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            className="container"
            style={{ maxWidth: '900px', paddingBottom: '4rem' }}
        >
            <header style={{ marginBottom: '3rem', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                <div>
                    <h1 style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                        <Zap className="text-primary" size={32} />
                        {lang === 'en' ? 'Your AI Study Plan' : 'Sizning AI O\'quv Rejangiz'}
                    </h1>
                    <p className="text-muted" style={{ fontSize: '1.1rem', marginTop: '0.5rem' }}>
                        {lang === 'en' ? 'Personalized roadmap generated by Atlas AI.' : 'Atlas AI tomonidan yaratilgan shaxsiy yo\'l xaritasi.'}
                    </p>
                </div>
                <button
                    onClick={generateAIPlan}
                    disabled={loading}
                    className="btn btn-ghost"
                    style={{ display: 'flex', gap: '0.5rem', color: 'var(--color-primary)' }}
                >
                    <RefreshCw size={18} className={loading ? 'animate-spin' : ''} />
                    {lang === 'en' ? 'Regenerate' : 'Yangilash'}
                </button>
            </header>

            <AnimatePresence mode="wait">
                {loading ? (
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        style={{ textAlign: 'center', padding: '4rem' }}
                    >
                        <Loader2 className="animate-spin text-primary" size={48} style={{ margin: '0 auto 1.5rem' }} />
                        <h3>{lang === 'en' ? 'Atlas is building your roadmap...' : 'Atlas reja tuzmoqda...'}</h3>
                    </motion.div>
                ) : error ? (
                    <div className="glass-panel text-center" style={{ padding: '3rem' }}>
                        <p className="text-error">{error}</p>
                        <button onClick={generateAIPlan} className="btn btn-primary" style={{ marginTop: '1.5rem' }}>Retry</button>
                    </div>
                ) : (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
                        {plan.map((item, idx) => (
                            <motion.div
                                key={idx}
                                initial={{ opacity: 0, x: -20 }}
                                animate={{ opacity: 1, x: 0 }}
                                transition={{ delay: idx * 0.1 }}
                                className="glass-panel"
                                style={{ padding: '1.5rem 2rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}
                            >
                                <div style={{ display: 'flex', alignItems: 'center', gap: '1.5rem' }}>
                                    <div style={{ background: 'var(--gradient-primary)', color: 'white', padding: '1rem', borderRadius: 'var(--radius-lg)', textAlign: 'center', minWidth: '70px', boxShadow: 'var(--shadow-glow)' }}>
                                        <span style={{ fontSize: '0.8rem', display: 'block', opacity: 0.8 }}>{lang === 'en' ? 'Day' : 'Kun'}</span>
                                        <strong style={{ fontSize: '1.5rem' }}>{item.day}</strong>
                                    </div>
                                    <div>
                                        <h3 style={{ marginBottom: '0.25rem' }}>{item.title}</h3>
                                        <p style={{ fontSize: '0.9rem', color: 'var(--color-text-main)', opacity: 0.8, marginBottom: '0.5rem' }}>{item.description}</p>
                                        <div style={{ display: 'flex', gap: '1rem', fontSize: '0.85rem', color: 'var(--color-text-muted)' }}>
                                            <span style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}><Calendar size={14} /> {item.duration}</span>
                                            <span style={{ color: 'var(--color-primary)', fontWeight: 600 }}>• {lang === 'en' ? 'Focus' : 'Fokus'}: {item.focus}</span>
                                        </div>
                                    </div>
                                </div>

                                <button className="btn btn-primary" style={{ padding: '0.75rem 1.5rem', borderRadius: 'var(--radius-lg)' }}>
                                    {lang === 'en' ? 'Start' : 'Boshlash'} <ArrowRight size={16} />
                                </button>
                            </motion.div>
                        ))}
                    </div>
                )}
            </AnimatePresence>
        </motion.div>
    );
};

export default Plan;
